// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD59n_PFSvMGIr_yQpySO0HzaYbWXXgUeA',
    appId: '1:970156244254:web:e3cec57e5892665ca21d0f',
    messagingSenderId: '970156244254',
    projectId: 'socialmediaapp-678ef',
    authDomain: 'socialmediaapp-678ef.firebaseapp.com',
    storageBucket: 'socialmediaapp-678ef.appspot.com',
    measurementId: 'G-6YS16YTTTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAR8DduuWEOwdR1Rt8AE1noA1gAbrGSJM',
    appId: '1:970156244254:android:553842ce4497c5e1a21d0f',
    messagingSenderId: '970156244254',
    projectId: 'socialmediaapp-678ef',
    storageBucket: 'socialmediaapp-678ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1bF2QmnfUuO2HWQi2RIy3omrnpnLTlXg',
    appId: '1:970156244254:ios:f0bd52c725d180d5a21d0f',
    messagingSenderId: '970156244254',
    projectId: 'socialmediaapp-678ef',
    storageBucket: 'socialmediaapp-678ef.appspot.com',
    iosBundleId: 'com.example.socialmediaapp.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD59n_PFSvMGIr_yQpySO0HzaYbWXXgUeA',
    appId: '1:970156244254:web:a7b4f8ba55fa9838a21d0f',
    messagingSenderId: '970156244254',
    projectId: 'socialmediaapp-678ef',
    authDomain: 'socialmediaapp-678ef.firebaseapp.com',
    storageBucket: 'socialmediaapp-678ef.appspot.com',
    measurementId: 'G-W3BDGCF5N2',
  );

}